name 'example42-timezone'
version '2.0.9'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-timezone'
summary 'Puppet module to manage timezones'
description 'This module manages the timezone on different OS'
dependency 'example42/puppi', '>=2.0.0'
